server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://dimonvideo.ru
#      name: dimonvideo.ru
#    - url: https://et-cetera.ru/mobile
#      name: et-cetera.ru